controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # CAMBIO AQUÍ: Usamos el controlador de trayectorias
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint_base_rotate
      - joint_shoulder
      - joint_elbow
      - joint_wrist
      - joint_gripper_rotate
      - joint_gripper_finger

    # Configuración específica para Trajectory Controller
    command_interfaces:
      - position
    state_interfaces:
      - position
    
    # Tolerancias (opcional, ayuda a que la trayectoria se complete sin errores)
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

# PIDs para Gazebo (se mantienen igual)
gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      joint_base_rotate: {p: 1000.0, i: 0.0, d: 200.0}
      joint_shoulder:    {p: 3000.0, i: 0.0, d: 500.0}
      joint_elbow:       {p: 5000.0, i: 0.0, d: 300.0}
      joint_wrist:       {p: 500.0, i: 10.0, d: 200.0}
      joint_gripper_rotate: {p: 100.0, i: 0.0, d: 13.0}
      joint_gripper_finger: {p: 100.0, i: 0.01, d: 10.0}
